# Generated by Django 6.0.8 on 2026-08-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_skill_proficiency_skill_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='email',
            new_name='personal_email',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='student_email',
            field=models.EmailField(default='kudelacruz@student.hau.edu.ph', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
    ]
