# Generated by Django 6.0.8 on 2026-08-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_email_personalinformation_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
