# Generated by Django 6.0.8 on 2026-08-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_inquiry_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimonies'},
        ),
    ]
