# Generated by Django 6.0.8 on 2026-10-03 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_tech_stack_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.techstack'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
